name: Deployment practice project 4
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Install dependencies
            working-directory: ./04_Practice_Project
            run: npm ci
          - name: Lint
            working-directory: ./04_Practice_Project           
            run: npm run lint
          - name: Test code
            working-directory: ./04_Practice_Project
            run: npm run test
          - name: Build
            working-directory: ./04_Practice_Project
            run: npm run build
          - name: Deploy code
            working-directory: ./04_Practice_Project
            run: echo "Deploying.."