name: Deployment practice project 4
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./04_Practice_Project
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Install dependencies
            run: npm ci
          - name: Lint          
            run: npm run lint
          - name: Test code
            run: npm run test
          - name: Build
            run: npm run build
          - name: Deploy code
            run: echo "Deploying.."